/*********************************************************************** 
* @ClassName 				: CCI_Constants
  @testClass				: None
* @Description 				: Constant Class
* @Reason for Class Sharing : Constant Class
* @Author 					: 
* @RevisionHistory 			: CH00
* @Version          Date              Changes made 
    CH00		    12/27/2020		  Initial Draft
************************************************************************/
public without sharing class CCI_Constants {
    
    
    /***********************************************************************
    @Description : Data type Constants values
	@Author 	 : SFDC
    ************************************************************************/
    public static final String AUTHTOKEN = 'Authtoken';
    public static final String USERNAME = 'Username';
    public static final String PASSWORD = 'Password';
    public static final String AUTH_HEADER = 'AuthHeader';
    public static final String AUTH_TYPE='AuthType';
   
}